日報の取得と削除の追加
TUT-SLP-lab/tarako-back pull request #9
Opened 2023-09-02 02:24 UTC by kittchy

2023-09-02 17:47 UTC, Hansyo requested changes
コメントにも書きましたが、`script/init_table.py`の変更はどっちでもいいです。

2023-09-02 17:47 UTC, Hansyo commented on app/diary/users/get_all_users_list.py
> +        )
複数行にしなくてよさそう。

2023-09-02 17:47 UTC, Hansyo commented on app/diary/users/get_all_users_list.py
> +            }
こんな感じで、判定を外に出した方が幸せかも

```suggestion
    if from_date is None and to_date is None:
        option = {
            "IndexName": "UserIndex",
        }
        datetime_range = None
    else:
        if from_date is not None and to_date is not None:
            datetime_range = Key("date").between(from_date, to_date)
        elif from_date is not None:
            datetime_range = Key("date").gte(from_date)
        elif to_date is not None:
            datetime_range = Key("date").lte(to_date)
        option = {
            "IndexName": "UserDateIndex",
        }

    user_daily_list = []
    for user in user_list:
            user_id_key = Key("user_id").eq(user)
            if datetime_range is not None:
                expr = user_id_key & datetime_range
            else:
                expr = user_id_key
            option["KeyConditionExpression"] = expr
```

2023-09-02 17:47 UTC, Hansyo commented on script/init_table.py
全体的に、
```python
from boto3.dynamodb.types import TypeSerializer
```
系統に直してもいいかも。
動いてるなら、無理に直す必要ないです。

2023-09-02 18:56 UTC, Hansyo approved these changes

2023-09-03 04:10 UTC, kittchy commented
@Hansyo 
AssumeRole付与してアクセスできることをかくにんしました！！！

2023-09-03 05:52 UTC, Hansyo approved these changes

2023-09-03 05:57 UTC, merged